### ISSUE TITLE
Error in console when having bricks in inventory

### ISSUE THREAD

**Issue by Floodo** [Twocoolguy/BrickThrower#8]
Hello there :) ... I have and issue on my Paper server v1.19 with BrickThrower v1.3.3 when I want to throw/or just have in inventory bricks, it gives this error into console :(

https://pastes.dev/xt0v9JtW5F

**Comment by Ethan-Passino** [comment]
Hi, have you been able to try out the latest version (2.0.0) and see if you still have this issue?

My apologies for the late reply, I've been gone for a while for personal reasons.

**Comment by Floodo** [comment]
Hello there :)) ... since the new version I didn't catch any error :)) .....If something will appear, I will let you know :)...... Thank you very much for quick fix!
